CREATE TABLE music (
    id INT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    on_spotify BOOLEAN,
    FOREIGN KEY (id) REFERENCES items(id)
);

CREATE TABLE genres (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);